import { Toaster } from "@/app/_components/ui/sonner"
import { GeistMono } from "geist/font/mono"
import { GeistSans } from "geist/font/sans"
import type { Metadata } from "next"
import { Footer } from "./_components/footer"
import { AuthProvider } from "./_providers/auth"
import "./globals.css"

export const metadata: Metadata = {
  title: "FSW Barber Shop",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="pt-BR"
      className={`dark ${GeistSans.variable} ${GeistMono.variable}`}
    >
      <body className="antialiased">
        <AuthProvider>
          <div className="flex h-full flex-col">
            <div className="flex-1">{children}</div>
            <Footer />
          </div>
        </AuthProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  )
}
